version: "3.7"
networks:
  dmz:
    name: public
    external: true
secrets:
  traefik_usersfile:
    external: true
services:
  jaeger:
    image: jaegertracing/all-in-one:1.17.1
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    deploy:
      labels:
        applicationPrefix: jaeger
        traefik.http.middlewares.auth.basicauth.usersfile: /run/secrets/usersfile
        traefik.http.routers.jaeger.middlewares: auth
        traefik.http.routers.jaeger.entrypoints: ${TRAEFIK_WEB_ENTRYPOINT:-web}
        traefik.http.services.jaeger.loadbalancer.server.port: 16686
    networks:
      - dmz
