version: "3.7"
networks:
  dmz:
    name: public
    external: true
secrets:
  traefik_usersfile:
    external: true
services:
  jaeger-query:
    image: jaegertracing/jaeger-query:1.17.1
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elastic1.lab.ryezone.com:9200,http://elastic2.lab.ryezone.com:9200,http://elastic3.lab.ryezone.com:9200,http://elastic4.lab.ryezone.com:9200,http://elastic5.lab.ryezone.com:9200,http://elastic6.lab.ryezone.com:9200
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role==worker
      labels:
        applicationPrefix: jaeger
        traefik.http.middlewares.auth.basicauth.usersfile: /run/secrets/usersfile
        traefik.http.routers.jaeger-query.middlewares: auth
        traefik.http.routers.jaeger-query.entrypoints: ${TRAEFIK_WEB_ENTRYPOINT:-web}
        traefik.http.services.jaeger-query.loadbalancer.server.port: 16686
    networks:
      - dmz
  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.17.1
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elastic1.lab.ryezone.com:9200,http://elastic2.lab.ryezone.com:9200,http://elastic3.lab.ryezone.com:9200,http://elastic4.lab.ryezone.com:9200,http://elastic5.lab.ryezone.com:9200,http://elastic6.lab.ryezone.com:9200
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role==worker
      labels:
        applicationPrefix: jaeger-collector
        traefik.http.middlewares.auth.basicauth.usersfile: /run/secrets/usersfile
        traefik.http.routers.jaeger-collector.middlewares: auth
        traefik.http.routers.jaeger-collector.entrypoints: ${TRAEFIK_WEB_ENTRYPOINT:-web}
        traefik.http.services.jaeger-collector.loadbalancer.server.port: 14269
    ports:
      - target: 14627
        published: 14627
        protocol: tcp
        mode: ingress
      - target: 14628
        published: 14628
        protocol: tcp
        mode: ingress
      - target: 14629
        published: 14629
        protocol: tcp
        mode: ingress
      - target: 14250
        published: 14250
        protocol: tcp
        mode: ingress
    networks:
      - dmz
  jaeger_agent:
    image: jaegertracing/jaeger-agent:1.17.1
    command: --reporter.grpc.host-port=jaeger-collector:14250
    deploy:
      mode: global
      labels:
        applicationPrefix: jaeger-agent
        traefik.http.middlewares.auth.basicauth.usersfile: /run/secrets/usersfile
        traefik.http.routers.jaeger_agent.middlewares: auth
        traefik.http.routers.jaeger_agent.entrypoints: ${TRAEFIK_WEB_ENTRYPOINT:-web}
        traefik.http.services.jaeger_agent.loadbalancer.server.port: 14271
    ports:
      - target: 6831
        published: 6831
        protocol: udp
        mode: host
      - target: 6832
        published: 6832
        protocol: udp
        mode: host
      - target: 5778
        published: 5778
        protocol: tcp
        mode: host
      - target: 5775
        published: 5775
        protocol: udp
        mode: host
      - target: 14271
        published: 14271
        protocol: tcp
        mode: host
    networks:
      - dmz