version: "3.7"
networks:
  graylog:
    name: graylog
    external: true
volumes:
  mongodb_master_data: {}
secrets:
  mongo_database_password:
    external: true
  mongo_keyfile:
    external: true
services:
  mongo1:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: admin
      MONGODB_DATABASE: graylog
      MONGODB_USERNAME: graylog
      MONGODB_PASSWORD: graylog
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_KEY_FILE: /run/secrets/mongo_keyfile
      MONGODB_ADVERTISED_HOSTNAME: mongo1
    deploy:
      labels:
        traefik.enable: 'false'
    secrets:
      - mongo_database_password
      - mongo_keyfile
    volumes:
      - type: volume
        source: mongodb_master_data
        target: /bitnami/mongodb
    networks:
      - graylog
  mongo2:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_PRIMARY_ROOT_PASSWORD: admin
      MONGODB_PRIMARY_HOST: mongo1
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_KEY_FILE: /run/secrets/mongo_keyfile
      MONGODB_ADVERTISED_HOSTNAME: mongo2
    deploy:
      labels:
        traefik.enable: 'false'
    secrets:
      - mongo_database_password
      - mongo_keyfile
    networks:
      - graylog
  mongo3:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_PRIMARY_ROOT_PASSWORD: admin
      MONGODB_PRIMARY_HOST: mongo1
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_KEY_FILE: /run/secrets/mongo_keyfile
      MONGODB_ADVERTISED_HOSTNAME: mongo3
    deploy:
      labels:
        traefik.enable: 'false'
    secrets:
      - mongo_database_password
      - mongo_keyfile
    networks:
      - graylog
