version: "3.7"
networks:
  dmz:
    name: public
volumes:
services:
  redis:
    image: redis:6.0-rc3
    deploy:
      labels:
        applicationPrefix: redis
        traefik.http.middlewares.auth.basicauth.usersfile: /run/secrets/usersfile
        traefik.http.routers.redis.middlewares: auth
        traefik.http.routers.redis.entrypoints: ${TRAEFIK_WEB_ENTRYPOINT:-web}
        traefik.http.services.redis.loadbalancer.server.port: 6379
    networks:
      - dmz
