version: "3.7"
networks:
  graylog:
    name: graylog
volumes:
  mongodb_master_data: {}
secrets:
  mongo_keyfile:
    external: true
  mongo_database_password:
    external: true
  mongo_root_password:
    external: true
services:
  mongo1:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: admin
      # MONGODB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
      # MONGODB_REPLICA_SET_KEY_FILE: /run/secrets/mongo_keyfile
      # MONGODB_ADVERTISED_HOSTNAME: mongo1
      # MONGODB_REPLICA_SET_MODE: primary
      # MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_DATABASE: graylog
      MONGODB_USERNAME: graylog
      MONGODB_PASSWORD: graylog
      # MONGODB_PASSWORD_FILE: /run/secrets/mongo_database_password
    secrets:
      - mongo_root_password
      - mongo_database_password
      - mongo_keyfile
    volumes:
      - type: volume
        source: mongodb_master_data
        target: /bitnami/mongodb
    networks:
      - graylog
    deploy:
      labels:
        traefik.enable: 'false'