version: "3.7"
networks:
  graylog:
    name: graylog

secrets:
  mongo_keyfile:
    external: true
  mongo_root_username:
    external: true
  mongo_root_password:
    external: true

volumes:
  mongodb_master_data: {}
  esdata1: {}
  esdata2: {}
  esdata3: {}

services:
  mongo1:
    image: bitnami/mongodb:4.2
    environment:
      MONGODB_ROOT_USER_FILE: /run/secrets/mongo_root_username
      MONGODB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
      MONGODB_REPLICA_SET_KEY_FILE: /run/secrets/mongo_keyfile
      MONGODB_ADVERTISED_HOSTNAME: mongo1
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
    secrets:
      - source: mongo_root_username
        target: mongo_root_username
      - source: mongo_root_password
        target: mongo_root_password
      - source: mongo_keyfile
        target: mongo_keyfile
    volumes:
      - type: volume
        source: mongodb_master_data
        target: /bitnami/mongodb
    networks:
      - graylog
    deploy:
      labels:
        traefik.enable: 'false'
  mongo2:
    image: bitnami/mongodb:4.2
    environment:
      MONGODB_ROOT_USER_FILE: /run/secrets/mongo_root_username
      MONGODB_PRIMARY_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
      MONGODB_REPLICA_SET_KEY_FILE: /run/secrets/mongo_keyfile
      MONGODB_ADVERTISED_HOSTNAME: mongo2
      MONGODB_PRIMARY_HOST: mongo1
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_REPLICA_SET_NAME: rs0
    secrets:
      - source: mongo_root_username
        target: mongo_root_username
      - source: mongo_root_password
        target: mongo_root_password
      - source: mongo_keyfile
        target: mongo_keyfile
    networks:
      - graylog
    deploy:
      labels:
        traefik.enable: 'false'
  mongo3:
    image: bitnami/mongodb:4.2
    environment:
      MONGODB_ROOT_USER_FILE: /run/secrets/mongo_root_username
      MONGODB_PRIMARY_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
      MONGODB_REPLICA_SET_KEY_FILE: /run/secrets/mongo_keyfile
      MONGODB_ADVERTISED_HOSTNAME: mongo3
      MONGODB_PRIMARY_HOST: mongo1
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_REPLICA_SET_NAME: rs0
    secrets:
      - source: mongo_root_username
        target: mongo_root_username
      - source: mongo_root_password
        target: mongo_root_password
      - source: mongo_keyfile
        target: mongo_keyfile
    networks:
      - graylog
    deploy:
      labels:
        traefik.enable: 'false'
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - cluster.name=graylog
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - graylog
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - cluster.name=graylog
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - graylog
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - cluster.name=graylog
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    networks:
      - graylog
