version: "3.7"
networks:
  graylog:
    name: graylog

secrets:
  mongo_keyfile:
    external: true
  mongo_database_password:
    external: true
  mongo_root_password:
    external: true
  graylog_password_secret:
    external: true
  graylog_root_password:
    external: true
  graylog_mongodb_uri:
    external: true
  

volumes:
  mongodb_master_data: {}
  graylog_data: {}
  esdata1: {}
  esdata2: {}
  esdata3: {}

services:
  mongo1:
    image: bitnami/mongodb:4.2
    environment:
      MONGODB_ROOT_USER_FILE: root
      MONGODB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
      MONGODB_REPLICA_SET_KEY_FILE: /run/secrets/mongo_keyfile
      MONGODB_ADVERTISED_HOSTNAME: mongo1
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_DATABASE: graylog
      MONGODB_USERNAME: graylog
      MONGODB_PASSWORD_FILE: /run/secrets/mongo_database_password
    secrets:
      - mongo_root_password
      - mongo_database_password
      - mongo_keyfile
    volumes:
      - type: volume
        source: mongodb_master_data
        target: /bitnami/mongodb
    networks:
      - graylog
    deploy:
      labels:
        traefik.enable: 'false'
  mongo2:
    image: bitnami/mongodb:4.2
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_PRIMARY_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
      MONGODB_REPLICA_SET_KEY_FILE: /run/secrets/mongo_keyfile
      MONGODB_ADVERTISED_HOSTNAME: mongo3
      MONGODB_PRIMARY_HOST: mongo1
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_REPLICA_SET_NAME: rs0
    secrets:
      - mongo_root_password
      - mongo_keyfile
    networks:
      - graylog
    deploy:
      labels:
        traefik.enable: 'false'
  mongo3:
    image: bitnami/mongodb:4.2
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_PRIMARY_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
      MONGODB_REPLICA_SET_KEY_FILE: /run/secrets/mongo_keyfile
      MONGODB_ADVERTISED_HOSTNAME: mongo3
      MONGODB_PRIMARY_HOST: mongo1
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_REPLICA_SET_NAME: rs0
    secrets:
      - mongo_root_password
      - mongo_keyfile
    networks:
      - graylog
    deploy:
      labels:
        traefik.enable: 'false'
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - cluster.name=graylog
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - graylog
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - cluster.name=graylog
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - graylog
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - cluster.name=graylog
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    networks:
      - graylog
  graylog1:
    image: graylog/graylog:3.2
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - elasticsearch1
      - elasticsearch2
      - elasticsearch3
    environment:
      GRAYLOG_IS_MASTER: 'true'
      GRAYLOG_PASSWORD_SECRET__FILE: /run/secrets/graylog_password_secret
      GRAYLOG_ROOT_PASSWORD_SHA2__FILE: /run/secrets/graylog_root_password
      GRAYLOG_MONGODB_URI__FILE: /run/secrets/graylog_mongodb_uri
      GRAYLOG_ROOT_EMAIL: ${LETS_ENCRYPT_EMAIL}
      GRAYLOG_HTTP_EXTERNAL_URI: https://graylog.${TOP_LEVEL_DOMAIN}/
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch1:9200,http://elasticsearch2:9200,http://elasticsearch3:9200
      GRAYLOG_ALLOW_LEADING_WILDCARD_SEARCHES: 'false'
      GRAYLOG_ALLOW_HIGHLIGHTING: 'false'
    secrets:
      - graylog_password_secret
      - graylog_root_password
      - graylog_mongodb_uri
    networks:
      - graylog
    volumes:
      - graylog_data:/usr/share/graylog/data
  # graylog2:
  #   image: graylog/graylog:3.2
  #   environment:
  #     GRAYLOG_IS_MASTER: 'false'
  #     GRAYLOG_PASSWORD_SECRET__FILE: /run/secrets/graylog_password_secret
  #     GRAYLOG_ROOT_PASSWORD_SHA2__FILE: /run/secrets/graylog_root_password
  #     GRAYLOG_MONGODB_URI__FILE: /run/secrets/graylog_mongodb_uri
  #     GRAYLOG_ROOT_EMAIL: ${LETS_ENCRYPT_EMAIL}
  #     GRAYLOG_HTTP_EXTERNAL_URI: https://graylog.${TOP_LEVEL_DOMAIN}
  #     GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch1:9200,http://elasticsearch2:9200,http://elasticsearch3:9200
  #     GRAYLOG_ALLOW_LEADING_WILDCARD_SEARCHES: 'false'
  #     GRAYLOG_ALLOW_HIGHLIGHTING: 'false'
  # graylog3:
  #   image: graylog/graylog:3.2
  #   environment:
  #     GRAYLOG_IS_MASTER: 'false'
  #     GRAYLOG_PASSWORD_SECRET__FILE: /run/secrets/graylog_password_secret
  #     GRAYLOG_ROOT_PASSWORD_SHA2__FILE: /run/secrets/graylog_root_password
  #     GRAYLOG_MONGODB_URI__FILE: /run/secrets/graylog_mongodb_uri
  #     GRAYLOG_ROOT_EMAIL: ${LETS_ENCRYPT_EMAIL}
  #     GRAYLOG_HTTP_EXTERNAL_URI: https://graylog.${TOP_LEVEL_DOMAIN}
  #     GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch1:9200,http://elasticsearch2:9200,http://elasticsearch3:9200
  #     GRAYLOG_ALLOW_LEADING_WILDCARD_SEARCHES: 'false'
  #     GRAYLOG_ALLOW_HIGHLIGHTING: 'false'
